return {
	['windowcontrol'] = {
		['functions'] = {
			['bringToFront'] = true,
			['destroy'] = true,
			['getName'] = true,
			['getPosition'] = true,
			['getScrollState'] = true,
			['getSize'] = true,
			['getTabTarget'] = true,
			['isEnabled'] = true,
			['isReadOnly'] = true,
			['isVisible'] = true,
			['onClickDown'] = true,
			['onClickRelease'] = true,
			['onClose'] = true,
			['onDoubleClick'] = true,
			['onDrag'] = true,
			['onDragEnd'] = true,
			['onDragStart'] = true,
			['onDrop'] = true,
			['onFirstLayout'] = true,
			['onHover'] = true,
			['onHoverUpdate'] = true,
			['onInit'] = true,
			['onMenuSelection'] = true,
			['onScroll'] = true,
			['onVisibilityChanged'] = true,
			['onWheel'] = true,
			['onZoom'] = true,
			['registerMenuItem'] = true,
			['resetAnchor'] = true,
			['resetMenuItems'] = true,
			['sendToBack'] = true,
			['setAnchor'] = true,
			['setAnchoredHeight'] = true,
			['setAnchoredWidth'] = true,
			['setBackColor'] = true,
			['setEnabled'] = true,
			['setFrame'] = true,
			['setHoverCursor'] = true,
			['setReadOnly'] = true,
			['setScrollPosition'] = true,
			['setStateFrame'] = true,
			['setStaticBounds'] = true,
			['setTabTarget'] = true,
			['setTooltipText'] = true,
			['setVisible'] = true,
		},
		['inherit'] = {},
	},
	['widget'] = {
		['functions'] = {
			['bringToFront'] = true,
			['destroy'] = true,
			['getSize'] = true,
			['sendToBack'] = true,
			['setEnabled'] = true,
			['setFrame'] = true,
			['setPosition'] = true,
			['setRadialPosition'] = true,
			['setVisible'] = true,
		},
		['inherit'] = {},
	},
	['dragdata'] = {
		['functions'] = {
			['addDie'] = true,
			['addShortcut'] = true,
			['createBaseData'] = true,
			['disableHotkeying'] = true,
			['getCustomData'] = true,
			['getDatabaseNode'] = true,
			['getDescription'] = true,
			['getDieList'] = true,
			['getMetaData'] = true,
			['getMetaDataList'] = true,
			['getNumberData'] = true,
			['getSecret'] = true,
			['getShortcutData'] = true,
			['getShortcutList'] = true,
			['getSlot'] = true,
			['getSlotCount'] = true,
			['getSlotType'] = true,
			['getStringData'] = true,
			['getTokenData'] = true,
			['getType'] = true,
			['isType'] = true,
			['nextSlot'] = true,
			['reset'] = true,
			['resetType'] = true,
			['revealDice'] = true,
			['setCustomData'] = true,
			['setData'] = true,
			['setDatabaseNode'] = true,
			['setDescription'] = true,
			['setDieList'] = true,
			['setIcon'] = true,
			['setMetaData'] = true,
			['setNumberData'] = true,
			['setSecret'] = true,
			['setShortcutData'] = true,
			['setSlot'] = true,
			['setSlotType'] = true,
			['setStringData'] = true,
			['setTokenData'] = true,
			['setType'] = true,
		},
		['inherit'] = {},
	},
	['databasenode'] = {
		['functions'] = {
			['addChildCategory'] = true,
			['addHolder'] = true,
			['createChild'] = true,
			['delete'] = true,
			['getCategory'] = true,
			['getChild'] = true,
			['getChildCategories'] = true,
			['getChildCount'] = true,
			['getChildren'] = true,
			['getDefaultChildCategory'] = true,
			['getHolders'] = true,
			['getModule'] = true,
			['getName'] = true,
			['getNodeName'] = true,
			['getOwner'] = true,
			['getParent'] = true,
			['getPath'] = true,
			['getRulesetVersion'] = true,
			['getText'] = true,
			['getType'] = true,
			['getValue'] = true,
			['getVersion'] = true,
			['isIntact'] = true,
			['isOwner'] = true,
			['isPublic'] = true,
			['isReadOnly'] = true,
			['isStatic'] = true,
			['onChildAdded'] = true,
			['onChildDeleted'] = true,
			['onChildUpdate'] = true,
			['onDelete'] = true,
			['onIntegrityChange'] = true,
			['onObserverUpdate'] = true,
			['onUpdate'] = true,
			['removeAllHolders'] = true,
			['removeChildCategory'] = true,
			['removeHolder'] = true,
			['revert'] = true,
			['setCategory'] = true,
			['setDefaultChildCategory'] = true,
			['setPublic'] = true,
			['setStatic'] = true,
			['setValue'] = true,
			['updateChildCategory'] = true,
			['updateVersion'] = true,
		},
		['inherit'] = {},
	},
	['windowinstance'] = {
		['functions'] = {
			['bringToFront'] = true,
			['close'] = true,
			['createControl'] = true,
			['getClass'] = true,
			['getControls'] = true,
			['getDatabaseNode'] = true,
			['getFrame'] = true,
			['getLockState'] = true,
			['getPosition'] = true,
			['getSize'] = true,
			['getTooltipText'] = true,
			['getViewers'] = true,
			['isMinimized'] = true,
			['isShared'] = true,
			['notifyUpdate'] = true,
			['onClose'] = true,
			['onDrop'] = true,
			['onFirstLayout'] = true,
			['onHover'] = true,
			['onHoverUpdate'] = true,
			['onInit'] = true,
			['onLockStateChanged'] = true,
			['onMenuSelection'] = true,
			['onMove'] = true,
			['onSizeChanged'] = true,
			['onSubwindowInstantiated'] = true,
			['onViewersChanged'] = true,
			['registerMenuItem'] = true,
			['resetMenuItems'] = true,
			['setBackColor'] = true,
			['setEnabled'] = true,
			['setFrame'] = true,
			['setLockState'] = true,
			['setPosition'] = true,
			['setSize'] = true,
			['setTooltipText'] = true,
			['share'] = true,
		},
		['inherit'] = {},
	},
	['widgetcontainer'] = { ['functions'] = { ['addBitmapWidget'] = true, ['addTextWidget'] = true }, ['inherit'] = {} },
	['tokeninstance'] = {
		['functions'] = {
			['addUnderlay'] = true,
			['clearTargets'] = true,
			['delete'] = true,
			['getContainerNode'] = true,
			['getContainerScale'] = true,
			['getId'] = true,
			['getImageSize'] = true,
			['getName'] = true,
			['getOrientation'] = true,
			['getPosition'] = true,
			['getPrototype'] = true,
			['getScale'] = true,
			['getTargetingIdentities'] = true,
			['getTargets'] = true,
			['isActivable'] = true,
			['isActive'] = true,
			['isModifiable'] = true,
			['isTargetable'] = true,
			['isTargeted'] = true,
			['isTargetedBy'] = true,
			['isTargetedByIdentity'] = true,
			['isVisible'] = true,
			['onActivation'] = true,
			['onClickDown'] = true,
			['onClickRelease'] = true,
			['onContainerChanged'] = true,
			['onContainerChanging'] = true,
			['onDelete'] = true,
			['onDoubleClick'] = true,
			['onDrag'] = true,
			['onDragEnd'] = true,
			['onDragStart'] = true,
			['onDrop'] = true,
			['onHover'] = true,
			['onHoverUpdate'] = true,
			['onMenuSelection'] = true,
			['onMove'] = true,
			['onScaleChanged'] = true,
			['onTargetUpdate'] = true,
			['onTargetedUpdate'] = true,
			['onWheel'] = true,
			['registerMenuItem'] = true,
			['removeAllUnderlays'] = true,
			['resetMenuItems'] = true,
			['setActivable'] = true,
			['setActive'] = true,
			['setContainerScale'] = true,
			['setModifiable'] = true,
			['setName'] = true,
			['setOrientation'] = true,
			['setOrientationMode'] = true,
			['setPosition'] = true,
			['setScale'] = true,
			['setTarget'] = true,
			['setTargetable'] = true,
			['setVisible'] = true,
		},
		['inherit'] = {},
	},
	['buttoncontrol'] = {
		['functions'] = {
			['getValue'] = true,
			['onButtonPress'] = true,
			['onValueChanged'] = true,
			['setColor'] = true,
			['setIcons'] = true,
			['setStateColor'] = true,
			['setStateIcons'] = true,
			['setStateText'] = true,
			['setStateTooltipText'] = true,
			['setText'] = true,
			['setTooltipText'] = true,
			['setValue'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['tokencontrol'] = {
		['functions'] = {
			['getPrototype'] = true,
			['onValueChanged'] = true,
			['populateFromImageNode'] = true,
			['setPrototype'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['tokenbag'] = { ['functions'] = { ['getZoom'] = true, ['setZoom'] = true },
                  ['inherit'] = { ['windowcontrol'] = true } },
	['subwindow'] = {
		['functions'] = { ['getValue'] = true, ['onInstanceCreated'] = true, ['setValue'] = true },
		['inherit'] = { ['windowcontrol'] = true },
	},
	['stringcontrol'] = {
		['functions'] = { ['getEmptyText'] = true, ['onValueChanged'] = true, ['setEmptyText'] = true },
		['inherit'] = { ['windowcontrol'] = true, ['textbasecontrol'] = true },
	},
	['scrollbarcontrol'] = { ['functions'] = { ['setTarget'] = true }, ['inherit'] = { ['windowcontrol'] = true } },
	['portraitselectioncontrol'] = {
		['functions'] = { ['activate'] = true, ['getFile'] = true, ['setFile'] = true },
		['inherit'] = { ['windowcontrol'] = true },
	},
	['genericcontrol'] = {
		['functions'] = { ['hasIcon'] = true, ['setColor'] = true, ['setIcon'] = true },
		['inherit'] = { ['windowcontrol'] = true },
	},
	['databasecontrol'] = { ['functions'] = { ['getDatabaseNode'] = true }, ['inherit'] = {} },
	['diecontrol'] = {
		['functions'] = {
			['addDie'] = true,
			['getDice'] = true,
			['isEmpty'] = true,
			['onValueChanged'] = true,
			['reset'] = true,
			['setDice'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['chatwindow'] = {
		['functions'] = {
			['addMessage'] = true,
			['clear'] = true,
			['deliverMessage'] = true,
			['onDiceLanded'] = true,
			['onDiceTotal'] = true,
			['onReceiveMessage'] = true,
			['throwDice'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['formattedtextcontrol'] = {
		['functions'] = {
			['isEmpty'] = true,
			['onGainFocus'] = true,
			['onLoseFocus'] = true,
			['onValueChanged'] = true,
			['setFocus'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['imagecontrol'] = {
		['functions'] = {
			['addToken'] = true,
			['clearSelectedTokens'] = true,
			['deleteDrawing'] = true,
			['enableGridPlacement'] = true,
			['getCursorMode'] = true,
			['getDistanceBetween'] = true,
			['getDrawingTool'] = true,
			['getGridHexElementDimensions'] = true,
			['getGridOffset'] = true,
			['getGridSize'] = true,
			['getGridSnap'] = true,
			['getGridType'] = true,
			['getImageSize'] = true,
			['getMaskTool'] = true,
			['getSelectedTokens'] = true,
			['getTokenLockState'] = true,
			['getTokenOrientationCount'] = true,
			['getTokenScale'] = true,
			['getTokens'] = true,
			['getTokensWithinDistance'] = true,
			['getViewpoint'] = true,
			['hasDrawing'] = true,
			['hasGrid'] = true,
			['hasMask'] = true,
			['hasTokens'] = true,
			['isTokenSelected'] = true,
			['onCursorModeChanged'] = true,
			['onDrawStateChanged'] = true,
			['onDrawingSizeChanged'] = true,
			['onGridStateChanged'] = true,
			['onMaskingStateChanged'] = true,
			['onMeasurePointer'] = true,
			['onMeasureVector'] = true,
			['onPointerSnap'] = true,
			['onTargetSelect'] = true,
			['onTokenAdded'] = true,
			['onTokenSnap'] = true,
			['preload'] = true,
			['resetPointers'] = true,
			['selectToken'] = true,
			['setCursorMode'] = true,
			['setDrawingSize'] = true,
			['setDrawingTool'] = true,
			['setGridOffset'] = true,
			['setGridSize'] = true,
			['setGridSnap'] = true,
			['setGridToolType'] = true,
			['setGridType'] = true,
			['setMaskEnabled'] = true,
			['setMaskTool'] = true,
			['setTokenLockState'] = true,
			['setTokenOrientationCount'] = true,
			['setTokenOrientationMode'] = true,
			['setTokenScale'] = true,
			['setViewpoint'] = true,
			['setViewpointCenter'] = true,
			['snapToGrid'] = true,
		},
		['inherit'] = { ['databasecontrol'] = true, ['windowcontrol'] = true },
	},
	['chatentry'] = {
		['functions'] = { ['onDeliverMessage'] = true, ['onSlashCommand'] = true },
		['inherit'] = { ['windowcontrol'] = true, ['textbasecontrol'] = true },
	},
	['buttonfield'] = { ['functions'] = {}, ['inherit'] = { ['databasecontrol'] = true, ['buttoncontrol'] = true } },
	['windowreferencefield'] = {
		['functions'] = {},
		['inherit'] = { ['databasecontrol'] = true, ['windowreferencecontrol'] = true },
	},
	['tokenfield'] = { ['functions'] = {}, ['inherit'] = { ['databasecontrol'] = true, ['tokencontrol'] = true } },
	['stringfield'] = { ['functions'] = {}, ['inherit'] = { ['databasecontrol'] = true, ['stringfield'] = true } },
	['numberfield'] = { ['functions'] = {}, ['inherit'] = { ['databasecontrol'] = true, ['numbercontrol'] = true } },
	['diefield'] = { ['functions'] = {}, ['inherit'] = { ['databasecontrol'] = true, ['diecontrol'] = true } },
	['formattedtextfield'] = {
		['functions'] = {},
		['inherit'] = { ['databasecontrol'] = true, ['formattedtextcontrol'] = true },
	},
	['scrollercontrol'] = { ['functions'] = {}, ['inherit'] = { ['windowcontrol'] = true } },
	['textwidget'] = {
		['functions'] = {
			['getText'] = true,
			['setColor'] = true,
			['setFont'] = true,
			['setMaxWidth'] = true,
			['setText'] = true,
		},
		['inherit'] = { ['widget'] = true },
	},
	['numbercontrol'] = {
		['functions'] = {
			['getFont'] = true,
			['getMaxValue'] = true,
			['getMinValue'] = true,
			['getValue'] = true,
			['hasFocus'] = true,
			['onChar'] = true,
			['onEnter'] = true,
			['onGainFocus'] = true,
			['onLoseFocus'] = true,
			['onTab'] = true,
			['onValueChanged'] = true,
			['setColor'] = true,
			['setDescriptionField'] = true,
			['setDescriptionText'] = true,
			['setFocus'] = true,
			['setFont'] = true,
			['setMaxValue'] = true,
			['setMinValue'] = true,
			['setValue'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['windowreferencecontrol'] = {
		['functions'] = {
			['activate'] = true,
			['getTargetDatabaseNode'] = true,
			['getValue'] = true,
			['isEmpty'] = true,
			['onValueChanged'] = true,
			['setIcons'] = true,
			['setValue'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
	['windowlist'] = {
		['functions'] = {
			['applyFilter'] = true,
			['applySort'] = true,
			['closeAll'] = true,
			['createWindow'] = true,
			['createWindowWithClass'] = true,
			['getColumnWidth'] = true,
			['getNextWindow'] = true,
			['getPrevWindow'] = true,
			['getWindowAt'] = true,
			['getWindowCount'] = true,
			['getWindows'] = true,
			['hasFocus'] = true,
			['onFilter'] = true,
			['onGainFocus'] = true,
			['onListChanged'] = true,
			['onListRearranged'] = true,
			['onLoseFocus'] = true,
			['onSortCompare'] = true,
			['scrollToWindow'] = true,
			['setColumnWidth'] = true,
			['setDatabaseNode'] = true,
			['setFocus'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true, ['databasecontrol'] = true },
	},
	['bitmapwidget'] = {
		['functions'] = { ['getBitmapName'] = true, ['setBitmap'] = true, ['setColor'] = true, ['setSize'] = true },
		['inherit'] = { ['widget'] = true },
	},
	['textbasecontrol'] = {
		['functions'] = {
			['getCursorPosition'] = true,
			['getFont'] = true,
			['getSelectionPosition'] = true,
			['getValue'] = true,
			['hasFocus'] = true,
			['isEmpty'] = true,
			['onChar'] = true,
			['onDeleteDown'] = true,
			['onDeleteUp'] = true,
			['onEnter'] = true,
			['onGainFocus'] = true,
			['onLoseFocus'] = true,
			['onNavigateDown'] = true,
			['onNavigateLeft'] = true,
			['onNavigateRight'] = true,
			['onNavigateUp'] = true,
			['onTab'] = true,
			['setColor'] = true,
			['setCursorPosition'] = true,
			['setFocus'] = true,
			['setFont'] = true,
			['setLine'] = true,
			['setSelectionPosition'] = true,
			['setUnderline'] = true,
			['setValue'] = true,
		},
		['inherit'] = { ['windowcontrol'] = true },
	},
}
